@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjcwMDM3ODB9.4Xr52IbWGPyDPrylKwg8pcadMm2BgRwKDu7BwMq5f3g

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}



### Orders create (signup)
POST http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "product_id": "1",
  "quantity": "1"
}

### Orders SHOW
GET http://localhost:3000/orders/1.json
Authorization: Bearer {{jwt}}


### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### PRODUCTS INDEX
GET http://localhost:3000/products.json

### Products show
GET http://localhost:3000/products/1.json
Authorization: Bearer {{jwt}}

### Products create
POST http://localhost:3000/products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "melon",
  "price": 5,
  "description": "yellow melon"
}

###Product update
PATCH http://localhost:3000/products/9.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "price": "20",
  "description": "overripe"
}

### Products destroy
DELETE  http://localhost:3000/products/10.json
Authorization: Bearer {{jwt}}