### Products index
GET http://localhost:3000/products.json

### Products show
GET http://localhost:3000/products/1.json

### Products create
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "melon",
  "price": 5,
  "image_url": "wwww.melon5.com",
  "discriptop": "yellow"
}