### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Products index
GET http://localhost:3000/products.json

### Products show
GET http://localhost:3000/products/1.json

### Products create
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "melon",
  "price": 5,
  "description": "yellow melon"
}

###Product update
PATCH http://localhost:3000/products/9.json
Content-Type: application/json

{
  "price": "20",
  "description": "overripe"
}

### Products destroy
DELETE  http://localhost:3000/products/10.json